Create  resources page issue 32
EugeneCodeCamp/EugeneCodeCamp.github.io pull request #40
Opened 2020-04-25 23:32 UTC by petrazoid

- added a page for resources (left existing section on the homepage)
- added nuxt-link to all the links on the nav bar with styling for active links (except for the ECC logo)

Before:
<img width="1211" alt="Screenshot 2020-04-25 at 4 30 45 PM" src="https://user-images.githubusercontent.com/10054415/80293204-4715e600-8712-11ea-814a-eca68741b7a6.png">

After:
<img width="1183" alt="Screenshot 2020-04-25 at 4 31 01 PM" src="https://user-images.githubusercontent.com/10054415/80293206-4f6e2100-8712-11ea-9e51-ae256cb9eae4.png">

This addresses https://github.com/EugeneCodeCamp/EugeneCodeCamp.github.io/issues/32.

2020-04-26 07:18 UTC, websupergirl commented
A few notes:

- The spacing is odd at the top but I think we may be fixing that with an addition to the top of that page in the future. I just want that to be a note for now.
- Somehow all the bullet points got centered in the columns. There should be 3 flexible columns but it should be left-align.
- The resources section needs to be removed off the front page.
- The subheader fonts seem to be less bold all over, but I'm going to make a separate bug ticket for that.

2020-04-26 20:54 UTC, antonioortegajr approved these changes

2020-04-28 07:29 UTC, websupergirl requested changes
Please fix the center-align on the column data and remove the content from the front page.

2020-05-02 04:59 UTC, petrazoid commented
Sorry for the delay! The list style is updated using (mostly) theme styling. I left the nested lists with bullets, removed the resources section from the main page.

2020-05-03 03:56 UTC, merged